### ISSUE TITLE
Loading spinner stuck after querying with ObjectID

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#117]
I'm getting this error after doing a query with just the objectID of a user. The query results now has a loading spinner that won't go away

```
error in evalInContext Invalid or unexpected token 5d1de06ba35c1c2507278268
loaded new documents
Uncaught (in promise) TypeError: undefined is not iterable!
    at e.exports.n.getIterator (renderer.js:1)
    at i.<anonymous> (renderer.js:1)
    at r (renderer.js:1)
    at Generator._invoke (renderer.js:1)
    at Generator.forEach.e.<computed> [as next] (renderer.js:1)
    at o (renderer.js:1)
    at renderer.js:1
    at processTicksAndRejections (internal/process/task_queues.js:85)
```

**Comment by Christilut** [comment]
Some more info on this: seems to happen when I query the production database instead of the local database. They both have the same collections.
Local database works fine.

**Comment by tothradoslav** [comment]
Your query is `5d1de06ba35c1c2507278268`? Without {_id: ObjectID(......}} ?

**Comment by Christilut** [comment]
Yeah, it should auto expand it right? But it doesn't do that when on the production database.

**Comment by Christilut** [comment]
Alright it does work when I enter it expanded: 
```
{
    _id: new ObjectID('5d1de06ba35c1c2507278268')
}
```

So I guess the problem is that it doesn't get expanded automatically. Only on the production database for some reason.

**Comment by tothradoslav** [comment]
Ok, I corrected the fact that it didnt' expand the query if a string ID is submitted. But this had nothing to do with your stuck spinner error.

Also, the `error in evalInContext Invalid or unexpected token 5d1de06ba35c1c2507278268` error is just a log for me, it's  not an actual error (just says eval didn't work, trying quicksearch).

So I didn't find the actual error, yet. Maybe this could help me find the issue:
1. does the document with that ID exist in production DB?
2. does this still happen when you try "Refresh" from context menu on project in the sidebar?

(I added some logs to see what happens, but this will only be in new version)

**Comment by Christilut** [comment]
Just tested it again: 
1. The ID exists in the production DB
2. Refresh doesn't seem to do anything, spinner keeps loading

It does show this on refresh though:
![image](https://user-images.githubusercontent.com/3471363/71960919-7d2c6a00-31f6-11ea-82fa-2707c9681eb6.png)

This error from console in the notification:
```
"SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/renderer.js:1:136381
    at C:\Users\Alpha\Documents\programs\mingo\resources\app.asar\node_modules\lodash\lodash.js:4905:15
    at baseForOwn (C:\Users\Alpha\Documents\programs\mingo\resources\app.asar\node_modules\lodash\lodash.js:2990:24)
    at C:\Users\Alpha\Documents\programs\mingo\resources\app.asar\node_modules\lodash\lodash.js:4874:18
    at Function.forEach (C:\Users\Alpha\Documents\programs\mingo\resources\app.asar\node_modules\lodash\lodash.js:9342:14)
    at file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/renderer.js:1:136337
    at r (file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/renderer.js:1:245368)
    at Generator._invoke (file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/renderer.js:1:246435)
    at Generator.forEach.e.<computed> [as next] (file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/renderer.js:1:245548)"
```

Might be unrelated though, I've seen this error notification before but haven't been able to reproduce it until now. Happens every refresh.

**Comment by tothradoslav** [comment]
I found where the unexpected token error came from. Could it be an issue with privileges on your production db? Mingo is trying to read your indexes.

**Comment by Christilut** [comment]
Don't think so. My production database is self hosted with just auth on the admin db, nothing special going on as far as I know. Any way I can check?

**Comment by tothradoslav** [comment]
I have added some logs and we'll see...

**Comment by Christilut** [comment]
```
error in evalInContext Invalid or unexpected token 5d1de06ba35c1c2507278268
this.filter.selectorParsed "{"_id":"5d1de06ba35c1c2507278268"}"
Uncaught (in promise) TypeError: undefined is not iterable!
    at e.exports.n.getIterator (renderer.js:1)
    at i.<anonymous> (renderer.js:1)
    at r (renderer.js:1)
    at Generator._invoke (renderer.js:1)
    at Generator.forEach.e.<computed> [as next] (renderer.js:1)
    at o (renderer.js:1)
    at renderer.js:1
    at processTicksAndRejections (internal/process/task_queues.js:85)
```

In the console currently

**Comment by tothradoslav** [comment]
Ok, this should be resolved in next version. Please let me know.
