### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by springzen** [mingo-app/mingo#274]
MacOS: 11.4

Steps: Attempt to open the application
Reinstall: solves nothing
Reboot: does not resolve the issue

Uncaught Exception:
TypeError: Cannot read property 'view' of undefined
at /Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:3417
at Array.filter (<anonymous>)
at t.a.i.a.Store.plugins (/Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:3366)
at /Applications/Mingo.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:355:46
at Array.forEach (<anonymous>)
at new Store (/Applications/Mingo.app/Contents/Resources/app.asar/node_modules/vuex/dist/vuex.common.js:355:11)
at Object.<anonymous> (/Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:2093)
at t (/Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:115)
at Object.<anonymous> (/Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:7406)
at t (/Applications/Mingo.app/Contents/Resources/app.asar/dist/electron/main.js:1:115)

![image](https://user-images.githubusercontent.com/2808006/125537110-8ef9b861-2a1a-48b4-ae6a-beca604e76bf.png)

**Comment by tothradoslav** [comment]
Thanks for this. What version of Mingo are you using?

So Mingo is not usable for you at all?

**Comment by springzen** [comment]
Thanks for looking into this. I am using v1.4.4, and yes, I cannot use Mingo at all. I wonder if macOS Big Sur is being restrictive in some way (i.e. disk access, etc).
I have downloaded v1.4.4 again today and the results were the same.

**Comment by tothradoslav** [comment]
Have you been able to use Mingo previously (older version) or you just launched it for the first time and didn't work?

**Comment by springzen** [comment]
First time on this machine, but ran it many times on a different machine. Same macOS version (Big Sur 11.4).

**Comment by tothradoslav** [comment]
This should be resolved in v1.4.5, please check it out. And let me know if it worked for you. Thank you!

**Comment by springzen** [comment]
Thank you so much. Mingo works perfectly now. 👍
