### ISSUE TITLE
Ubuntu crash

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#616]
Hi there, it's crashing in Ubuntu

Mixpanel tracking error ReferenceError: document is not defined
    at MixpanelPeople.<anonymous> (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/node_modules/mixpanel-browser/dist/mixpanel.cjs.js:5383:60)
    at MixpanelPeople.set (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/node_modules/mixpanel-browser/dist/mixpanel.cjs.js:2763:27)
    at /tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:16803
    at r (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:76707)
    at Generator._invoke (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:77774)
    at forEach.e.<computed> [as next] (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:76887)
    at a (/tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:1221)
    at /tmp/.mount_Mingo-DMn3sC/resources/app.asar/dist/electron/main.js:1:1324

**Comment by tothradoslav** [comment]
Please give me more information, such as: Does this happen on start? Or later on during execution?

**Comment by jgauna** [comment]
The app starts but suddenly it turns all white and you can't do/see anything. About 5-10 seconds after it starts
